// This file is auto-generated by @hey-api/openapi-ts

export const $ErrorResponse = {
    properties: {
        code: {
            type: 'string'
        },
        error: {
            type: 'string'
        }
    },
    required: ['error', 'code'],
    type: 'object'
} as const;

export const $Field = {
    properties: {
        required: {
            type: 'boolean'
        },
        type: {
            enum: ['string', 'bool'],
            type: 'string'
        },
        unique: {
            type: 'boolean'
        }
    },
    required: ['type', 'required', 'unique'],
    type: 'object'
} as const;

export const $FieldConfig = {
    properties: {
        participation: {
            additionalProperties: {
                '$ref': '#/definitions/Field'
            },
            type: 'object'
        },
        user: {
            additionalProperties: {
                '$ref': '#/definitions/Field'
            },
            type: 'object'
        }
    },
    required: ['user', 'participation'],
    type: 'object'
} as const;

export const $Game = {
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name'],
    type: 'object'
} as const;

export const $GetGameResponse = {
    '$ref': '#/definitions/Game'
} as const;

export const $GetGamesResponse = {
    items: {
        '$ref': '#/definitions/Game'
    },
    type: 'array'
} as const;

export const $GetParticipationMethodsResponse = {
    items: {
        '$ref': '#/definitions/ParticipationMethod'
    },
    type: 'array'
} as const;

export const $GetPrizesResponse = {
    items: {
        '$ref': '#/definitions/Prize'
    },
    type: 'array'
} as const;

export const $GetUserResponse = {
    '$ref': '#/definitions/User'
} as const;

export const $GetUsersResponse = {
    items: {
        '$ref': '#/definitions/User'
    },
    type: 'array'
} as const;

export const $GetWonPrizesResponse = {
    items: {
        '$ref': '#/definitions/WonPrize'
    },
    type: 'array'
} as const;

export const $Participation = {
    properties: {
        created_at: {},
        fields: {
            additionalProperties: {},
            type: 'object'
        },
        participation_id: {
            type: 'string'
        },
        participation_method_id: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        }
    },
    required: ['participation_id', 'participation_method_id', 'user_id', 'created_at', 'fields'],
    type: 'object'
} as const;

export const $ParticipationMethod = {
    properties: {
        fields: {
            '$ref': '#/definitions/FieldConfig'
        },
        game_id: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        limit: {
            enum: ['none', 'daily'],
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'game_id', 'name', 'limit', 'fields'],
    type: 'object'
} as const;

export const $ParticipationRequest = {
    properties: {
        fields: {
            additionalProperties: {},
            type: 'object'
        }
    },
    required: ['fields'],
    type: 'object'
} as const;

export const $ParticipationResponse = {
    properties: {
        prizes: {
            items: {
                '$ref': '#/definitions/PublicPrize'
            },
            type: 'array'
        }
    },
    required: ['prizes'],
    type: 'object'
} as const;

export const $Prize = {
    properties: {
        count: {
            format: 'int64',
            type: 'integer'
        },
        description: {
            type: 'string'
        },
        gameId: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'gameId', 'name', 'description', 'count'],
    type: 'object'
} as const;

export const $PublicPrize = {
    properties: {
        description: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['name', 'description'],
    type: 'object'
} as const;

export const $User = {
    properties: {
        additional_fields: {
            additionalProperties: {},
            type: 'object'
        },
        address: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        game_id: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        phone: {
            type: 'string'
        }
    },
    required: ['id', 'game_id', 'email', 'address', 'phone', 'additional_fields'],
    type: 'object'
} as const;

export const $WonPrize = {
    properties: {
        participation: {
            '$ref': '#/definitions/Participation'
        },
        prize: {
            '$ref': '#/definitions/Prize'
        },
        user: {
            '$ref': '#/definitions/User'
        }
    },
    required: ['prize', 'participation', 'user'],
    type: 'object'
} as const;