// This file is auto-generated by @hey-api/openapi-ts

export type CreatePrizeRequest = {
    count: number;
    description?: string;
    game_id: string;
    image_url?: string;
    name: string;
};

export type DrawMethod = {
    data: string;
    draw_method_id: string;
    game_id: string;
    method: 'first_n' | 'chance';
    name: string;
};

export type ErrorResponse = {
    code: string;
    error: string;
};

export type Field = {
    required: boolean;
    type: 'string' | 'bool';
    unique: boolean;
};

export type FieldConfig = {
    participation: {
        [key: string]: Field;
    };
    user: {
        [key: string]: Field;
    };
};

export type Game = {
    google_sheet_id?: string;
    google_sheet_tab_name?: string;
    id: string;
    name: string;
};

export type GetDrawMethodsResponse = Array<DrawMethod>;

export type GetGameResponse = Game;

export type GetGamesResponse = Array<Game>;

export type GetParticipationMethodsResponse = Array<ParticipationMethod>;

export type GetPrizesResponse = Array<Prize>;

export type GetUserResponse = User;

export type GetUsersResponse = Array<User>;

export type GetWonPrizesResponse = Array<WonPrize>;

export type Participation = {
    created_at: unknown;
    fields: {
        [key: string]: unknown;
    };
    participation_id: string;
    participation_method_id: string;
    user_id: string;
};

export type ParticipationMethod = {
    fields: FieldConfig;
    game_id: string;
    id: string;
    name: string;
    participation_limit: 'none' | 'daily';
};

export type ParticipationRequest = {
    fields: {
        [key: string]: unknown;
    };
};

export type ParticipationResponse = {
    prizes: Array<PublicPrize>;
};

export type Prize = {
    count: number;
    description?: string;
    game_id: string;
    id: string;
    image_url?: string;
    name: string;
    won_count: number;
};

export type PublicPrize = {
    description?: string;
    image_url?: string;
    name: string;
};

export type UpdateParticipationMethodRequest = {
    fields: FieldConfig;
    lose_mail_template_id?: string;
    name: string;
    participation_limit: 'none' | 'daily';
    win_mail_template_id?: string;
};

export type UpdatePrizeRequest = {
    count?: number;
    description?: string;
    image_url?: string;
    name?: string;
};

export type User = {
    additional_fields: {
        [key: string]: unknown;
    };
    address?: string;
    email?: string;
    game_id: string;
    id: string;
    phone?: string;
};

export type WonPrize = {
    participation: Participation;
    prize: Prize;
    user: User;
};

export type GetDrawMethodsData = {
    query?: {
        game_id?: string;
        participation_id?: string;
    };
};

export type GetDrawMethodsResponse2 = GetDrawMethodsResponse;

export type GetDrawMethodsError = ErrorResponse;

export type GetGamesResponse2 = GetGamesResponse;

export type GetGamesError = ErrorResponse;

export type GetGameData = {
    path: {
        gameId: string;
    };
};

export type GetGameResponse2 = Game;

export type GetGameError = ErrorResponse;

export type GetParticipationMethodsData = {
    query?: {
        game_id?: string;
    };
};

export type GetParticipationMethodsResponse2 = GetParticipationMethodsResponse;

export type GetParticipationMethodsError = ErrorResponse;

export type UpdateParticipationMethodData = {
    body: UpdateParticipationMethodRequest;
    path: {
        participationMethodId: string;
    };
};

export type UpdateParticipationMethodResponse = void;

export type UpdateParticipationMethodError = ErrorResponse;

export type UnlinkDrawMethodData = {
    path: {
        drawMethodId: string;
        participationMethodId: string;
    };
};

export type UnlinkDrawMethodResponse = void;

export type UnlinkDrawMethodError = ErrorResponse;

export type LinkDrawMethodData = {
    path: {
        drawMethodId: string;
        participationMethodId: string;
    };
};

export type LinkDrawMethodResponse = void;

export type LinkDrawMethodError = ErrorResponse;

export type GetPrizesData = {
    query?: {
        game_id?: string;
    };
};

export type GetPrizesResponse2 = GetPrizesResponse;

export type GetPrizesError = ErrorResponse;

export type CreatePrizeData = {
    body?: CreatePrizeRequest;
};

export type CreatePrizeResponse = unknown;

export type CreatePrizeError = ErrorResponse;

export type DeletePrizeData = {
    path: {
        prizeId: string;
    };
};

export type DeletePrizeResponse = void;

export type DeletePrizeError = ErrorResponse;

export type UpdatePrizeData = {
    body?: UpdatePrizeRequest;
    path: {
        prizeId: string;
    };
};

export type UpdatePrizeResponse = void;

export type UpdatePrizeError = ErrorResponse;

export type GetUsersData = {
    query?: {
        game_id?: string;
    };
};

export type GetUsersResponse2 = GetUsersResponse;

export type GetUsersError = ErrorResponse;

export type GetUserData = {
    path: {
        userId: string;
    };
};

export type GetUserResponse2 = User;

export type GetUserError = ErrorResponse;

export type GetWonPrizesData = {
    query?: {
        game_id?: string;
        prize_id?: string;
        user_id?: string;
    };
};

export type GetWonPrizesResponse2 = GetWonPrizesResponse;

export type GetWonPrizesError = ErrorResponse;

export type $OpenApiTs = {
    '/draw-methods': {
        get: {
            req: GetDrawMethodsData;
            res: {
                /**
                 * GetDrawMethodsResponse
                 */
                '200': GetDrawMethodsResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/games': {
        get: {
            res: {
                /**
                 * GetGamesResponse
                 */
                '200': GetGamesResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/games/{gameId}': {
        get: {
            req: GetGameData;
            res: {
                /**
                 * GetGameResponse
                 */
                '200': Game;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/participation-methods': {
        get: {
            req: GetParticipationMethodsData;
            res: {
                /**
                 * GetParticipationMethodsResponse
                 */
                '200': GetParticipationMethodsResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/participation-methods/{participationMethodId}': {
        put: {
            req: UpdateParticipationMethodData;
            res: {
                '204': void;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/participation-methods/{participationMethodId}/draw-methods/{drawMethodId}': {
        delete: {
            req: UnlinkDrawMethodData;
            res: {
                '204': void;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
        post: {
            req: LinkDrawMethodData;
            res: {
                '204': void;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/prizes': {
        get: {
            req: GetPrizesData;
            res: {
                /**
                 * GetPrizesResponse
                 */
                '200': GetPrizesResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
        post: {
            req: CreatePrizeData;
            res: {
                '201': unknown;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/prizes/{prizeId}': {
        delete: {
            req: DeletePrizeData;
            res: {
                '204': void;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
        put: {
            req: UpdatePrizeData;
            res: {
                '204': void;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/users': {
        get: {
            req: GetUsersData;
            res: {
                /**
                 * GetUsersResponse
                 */
                '200': GetUsersResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/users/{userId}': {
        get: {
            req: GetUserData;
            res: {
                /**
                 * GetUserResponse
                 */
                '200': User;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
    '/won-prizes': {
        get: {
            req: GetWonPrizesData;
            res: {
                /**
                 * GetWonPrizesResponse
                 */
                '200': GetWonPrizesResponse;
                /**
                 * ErrorResponse
                 */
                '400': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '403': ErrorResponse;
                /**
                 * ErrorResponse
                 */
                '500': ErrorResponse;
            };
        };
    };
};